### ISSUE TITLE
Integrate open-physiology-manifest into the editor

### ISSUE THREAD

**Issue by mhelvens** [open-physiology/nested-resource-editor#21]
* It is passed as a parameter (like the model library is now)
* The model library is no longer known by the widget.
* Commit and rollback buttons should be tied to Angular 2 event attributes.

**Comment by albatros13** [comment]
Can we create new resources with just manifest?
When adding new resources as properties of other resources, e.g., a new node to a border of a layer of a lyph A which is a segment of lyph B..., it is unfeasible to pass the output event to the very top level and then go through the chain of all involved components to update the corresponding property, and set the newly created entity as selected/highlighted so that user does not loose focus. 
We need to create a new node locally, e.g., 
let newNode = manifest.Node.new({}) 
and then link it to the involved property, i.e., propertyUpdated.emit({'nodes', newNode}), after that other components will be notified about the border change via model library ValueTracker

**Comment by mhelvens** [comment]
From just reading your question, I'm not sure why passing it through the chain would be infeasible. Maybe I misunderstand. Let's discuss it on Monday.
